<script setup lang="ts">
definePageMeta({ layout: false })

const route = useRoute()
const requestURL = useRequestURL()
const canonical = computed(() => new URL(route.path, requestURL.origin).toString())

useSeoMeta({
  title: 'Terms of Service | ScopeSight',
  description: 'Terms of Service for ScopeSight, the AI-powered newsletter analysis platform.',
  ogTitle: 'Terms of Service | ScopeSight',
  ogDescription: 'Terms of Service for ScopeSight.',
})

useHead({
  link: [{ rel: 'canonical', href: canonical }],
})
</script>

<template>
  <div class="min-h-screen bg-[var(--ui-bg)]">
    <UHeader :ui="{ root: 'border-b border-[var(--ui-border)]' }">
      <template #left>
        <NuxtLink to="/" class="inline-flex items-center gap-2 text-sm font-semibold">
          <span class="inline-flex size-7 items-center justify-center rounded-md bg-[var(--ui-primary)] text-[var(--ui-bg)]">
            SS
          </span>
          ScopeSight
        </NuxtLink>
      </template>

      <template #right>
        <UButton to="/" color="neutral" variant="ghost" label="Back to home" icon="i-lucide-arrow-left" />
      </template>
    </UHeader>

    <UContainer class="max-w-3xl py-12">
      <div class="prose prose-neutral dark:prose-invert max-w-none">
        <h1>Terms of Service</h1>
        <p class="text-lg text-[var(--ui-text-muted)]">
          Last updated: February 2025
        </p>

        <h2>1. Acceptance of Terms</h2>
        <p>
          By accessing or using ScopeSight ("the Service"), you agree to be bound by these Terms of Service. If you do not agree to these terms, do not use the Service.
        </p>

        <h2>2. Description of Service</h2>
        <p>
          ScopeSight is a SaaS platform that analyzes newsletters using artificial intelligence to extract recurring pain points, trends, and product opportunities. The Service processes newsletter content you provide and returns structured analyses.
        </p>

        <h2>3. User Accounts</h2>
        <p>
          You must create an account to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activities that occur under your account. You agree to provide accurate and complete information when creating your account.
        </p>

        <h2>4. Subscriptions and Payments</h2>
        <p>
          The Service offers paid subscription plans. Payments are processed through Stripe. By subscribing to a paid plan, you authorize us to charge your payment method on a recurring basis until you cancel. Prices are displayed in USD and may be subject to applicable taxes.
        </p>
        <p>
          You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period. No refunds are provided for partial billing periods.
        </p>

        <h2>5. Intellectual Property</h2>
        <p>
          <strong>Your content:</strong> You retain all rights to the newsletter content you submit to the Service. We do not claim ownership of your content.
        </p>
        <p>
          <strong>Our service:</strong> The Service, including its design, features, and underlying technology, is owned by ScopeSight. You may not copy, modify, or reverse-engineer any part of the Service.
        </p>
        <p>
          <strong>Analysis output:</strong> The analyses generated by the Service from your content are yours to use as you see fit.
        </p>

        <h2>6. Acceptable Use</h2>
        <p>
          You agree not to use the Service to process content you do not have the right to use, to attempt to disrupt or overload the Service, or to use the Service for any illegal purpose.
        </p>

        <h2>7. Limitation of Liability</h2>
        <p>
          The Service is provided "as is" without warranties of any kind. ScopeSight shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the Service. AI-generated analyses are informational and should not be relied upon as the sole basis for business decisions.
        </p>

        <h2>8. Termination</h2>
        <p>
          We may suspend or terminate your account if you violate these terms. You may delete your account at any time through the Settings page. Upon termination, your data will be retained for 30 days before permanent deletion.
        </p>

        <h2>9. Changes to Terms</h2>
        <p>
          We may update these Terms from time to time. We will notify you of material changes via email or through the Service. Continued use after changes constitutes acceptance.
        </p>

        <h2>10. Governing Law</h2>
        <p>
          These Terms are governed by and construed in accordance with the laws of France. Any disputes shall be subject to the exclusive jurisdiction of the courts of Paris, France.
        </p>

        <h2>11. Contact</h2>
        <p>
          For questions about these Terms, contact us at <a href="mailto:support@scopesight.app">support@scopesight.app</a>.
        </p>

        <USeparator class="my-10" />

        <h2>Version fran&ccedil;aise (r&eacute;sum&eacute;)</h2>
        <p>
          En utilisant ScopeSight, vous acceptez les pr&eacute;sentes conditions. Le service analyse vos newsletters par intelligence artificielle pour en extraire des signaux produit. Vous conservez la propri&eacute;t&eacute; de votre contenu. Les paiements sont g&eacute;r&eacute;s par Stripe. Le service est fourni &laquo;&nbsp;en l'&eacute;tat&nbsp;&raquo;, sans garantie. Vous pouvez supprimer votre compte &agrave; tout moment ; vos donn&eacute;es seront conserv&eacute;es 30 jours avant suppression d&eacute;finitive. Le droit fran&ccedil;ais s'applique, avec comp&eacute;tence exclusive des tribunaux de Paris.
        </p>
      </div>

      <div class="mt-12">
        <UButton to="/" color="neutral" variant="ghost" label="Back to home" icon="i-lucide-arrow-left" />
      </div>
    </UContainer>
  </div>
</template>
